### ISSUE TITLE
Supress `_copy_chunk(...)` prints during execution? 

### ISSUE THREAD

**Issue by jbusecke** [pangeo-data/rechunker#105]
Whenever I execute a rechunking plan in the recent rechunker versions, I get a ton of messages like this displayed:

```
_copy_chunk((slice(0, 100, None), slice(0, 25, None), slice(0, 53, None)))
```

Is it possible to suppress those? Or am I missing something here?

**Comment by aulemahal** [comment]
As a user, I would suggest moving the `print` call to a `logging.debug`, enabling finer control on whether it is printed out or not.

**Comment by TomAugspurger** [comment]
Agreed with changing those print to log messages.

**Comment by rabernat** [comment]
This is definitely a mistake left in the code by me. Sorry about that folks.
