### ISSUE TITLE
Package nitpicks

### ISSUE THREAD

**Issue by TomAugspurger** [pangeo-data/rechunker#11]
Just a collection of style things that can be safely ignored.

1. `rechunker.api`: I'm not a fan of `.api` namespaces. If something is in a public module then it's in the API. If it's in a private module (leading underscore) then it's not. No need for a `.api` namespace. However, we probably want the algorithm to be generic (no assumption of dask, zarr), so maybe we expose this in a `rechunker.dask` module?
2. `rechunk_zarr2zarr_w_dask` I think exposes a bit too much of the implementation into the function name. How about `rechunker.dask.rechunk(...)`. And we find some kind of interface for what the storage needs to define (`empty`, how to build a dask array from this thing, etc.). Then I can imagine a `rechunker.dask.rechunk` that rechunks with anything implementing that interface using Dask.

**Comment by rabernat** [comment]
Thanks for the tips! I'll incorporate these changes into the PR I'm working on for #4.

**Comment by TomAugspurger** [comment]
Nothing left to do here.
