### ISSUE TITLE
New release to fix read_only error?

### ISSUE THREAD

**Issue by rsignell-usgs** [pangeo-data/rechunker#137]
The [read_only error has been fixed in the master branch](https://github.com/pangeo-data/rechunker/pull/136), but could a new release be issued so we can easily update the conda package?

**Comment by rabernat** [comment]
0.5.1 is being pushed now - https://github.com/pangeo-data/rechunker/actions/runs/4417212663

Rich, would you be interested in becoming a rechunker maintainer? The bus factor is pretty low here. 🚌

**Comment by rsignell-usgs** [comment]
Sure!

**Comment by ocefpaf** [comment]
@rsignell-usgs just asked me about the conda-forge updates. Those are automatic as soon as a new release hits PyPI.

Also, I can send a quick PR that adds the PyPI releases with a GH tag. Hold on...

**Comment by rabernat** [comment]
Great @ocefpaf! Note that we already have https://github.com/pangeo-data/rechunker/blob/master/.github/workflows/release.yaml

**Comment by ocefpaf** [comment]
Just found that. Is it broken? Investigating...

**Comment by rabernat** [comment]
It's not broken. It works fine! The only part I don't like is that you have to create the tag with git on the command line, rather than in github.

**Comment by ocefpaf** [comment]
OK. Let me see if I can improve that.

**Comment by ocefpaf** [comment]
xref.: https://github.com/pangeo-data/rechunker/pull/138
