### ISSUE TITLE
maintenance of rechunker

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/rechunker#39]
I'm thrilled to see folks contributing to this package spontaneously. Since our first release, we have had PRs from @tomwhite, @davidbrochart, and @shoyer. We have quite a bit of momentum here, and I really like where the package is going.

I'm about to go on vacation for two weeks. Rather than have development stall during that time, I'd love to to expand the list of maintainers for this package beyond just me and @TomAugspurger.

Is anyone named above able to commit to reviewing PRs / responding to issues? If so, we are very happy to give you maintainer status on the repo.

**Comment by davidbrochart** [comment]
Thanks @rabernat, even if I've not really contributed yet. I'm not sure I can be a maintainer, since I don't know the package enough. And I'm also going to go on vacation in one week. So I can't commit to it, but I'll try and help if I can.

**Comment by shoyer** [comment]
I can't make any long term commitments, but I've made enough PRs in the past week that I suppose I really should sign up for helping out on maintenance, too :)

**Comment by tomwhite** [comment]
I've been away for the last week, so haven't followed any of the changes :) I've only made two minor PRs, but I'd be happy to help out if I can.

**Comment by TomAugspurger** [comment]
Congrats, you've all been invited :) Thanks for your help so far.

**Comment by rabernat** [comment]
Hi everyone! I'm back from vacation. Thanks so much for all your work over the past two weeks. It's great to see this project thriving!
