### ISSUE TITLE
Rechunk xarray

### ISSUE THREAD

**Issue by tomwhite** [pangeo-data/rechunker#45]
It would be useful to be able to use rechunker directly on an [xarray](http://xarray.pydata.org/en/stable/) Dataset (or DataArray), similar to the xarray [chunk](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.chunk.html) method.

**Comment by rabernat** [comment]
Yes absolutely. This is in fact the most likely way users would want to interact with rechunker.

One challenge is that xarray does not (easily) expose the underlying stores that were used to create the Dataset objects. (Those may not even exist if the data has been modified from its on-disk version.) What we could easily do in the short term would be to work with the dask arrays (as implemented in #27) for each variable.

**Comment by tomwhite** [comment]
Fixed in #52
