### ISSUE TITLE
Use pre-commit in build instead of calling flake8/black

### ISSUE THREAD

**Issue by eric-czech** [pangeo-data/rechunker#49]
Is there any reason that the pre-commit hook isn't run as part of the build rather than by calling the same steps directly?  I'm looking at: https://github.com/pangeo-data/rechunker/blob/b3e9628b0578472f6cfb55be79e2eabb504ba2b6/.github/workflows/ci.yaml#L43-L48

The build in https://github.com/pangeo-data/rechunker/pull/48 is (I think) failing because the pre-commit hook I ran locally is [pinned to black 19.10b0](https://github.com/pangeo-data/rechunker/blob/b3e9628b0578472f6cfb55be79e2eabb504ba2b6/.pre-commit-config.yaml#L2-L3) while the ci run is using the latest version (20.8b1).

**Comment by TomAugspurger** [comment]
Closed by #50
