### ISSUE TITLE
Rechunker paper for PASC

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/rechunker#69]
I would like to write a paper about rechunker for the Platform for Advanced Scientific Computing (PASC) Conference.

https://pasc21.pasc-conference.org/submission/guidelines-for-papers/

The deadline is Dec. 13, so quite tight. But I think I can pull it off. This is a short conference proceeding (10 pages all inclusive.)

All contributors are invited to join as authors, if you are game for some last minute writing. 😉

**Comment by rabernat** [comment]
Single-author paper submitted.

**Comment by rabernat** [comment]
Just a quick update. My PASC submission was rejected as not sufficiently novel! 😢 

I think JOSS is the next step.

**Comment by shoyer** [comment]
🙄

JOSS sounds like a great alternative.
