### ISSUE TITLE
Rechunker 0.4 requires Dask and Prefect

### ISSUE THREAD

**Issue by tomwhite** [pangeo-data/rechunker#82]
It looks like the changes in #77 mean that Prefect (and Dask) are now required, which seems like an inadvertent change.

I noticed this in https://github.com/pystatgen/sgkit/issues/530.

**Comment by TomAugspurger** [comment]
Agreed, that wasn't intentional.

Do we just need to make the prefect import at https://github.com/pangeo-data/rechunker/pull/77/files#diff-3dfce265445fa41c7ca0059e55990be70becc0eacead2d147ee39840fba1db27R1-R3 lazy / put in a try / except block?

**Comment by rabernat** [comment]
Rechunker 0.4.1 is now on pypi. @tomwhite, do you want to confirm that it actually resolves your original problem? #85 was a quick fix and doesn't actually explicitly test that you can import rechunker without the optional dependencies.

**Comment by tomwhite** [comment]
Unfortunately #85 didn't fix the issue. I've opened #87 which fixes the issue.

> #85 was a quick fix and doesn't actually explicitly test that you can import rechunker without the optional dependencies.

It would be good to add such a test if someone has time.

**Comment by rabernat** [comment]
Ok thanks for checking. Should we also revert #85?

**Comment by rabernat** [comment]
Ok hopefully 0.4.2 does the trick 😉 ! Thanks for your patience with this error and for your help fixing my mistake.

FWIW, dask[array] has been a required dependency for a while:
https://github.com/pangeo-data/rechunker/blob/40f2aa945cce73dea7e5239434016f7ed55218a6/setup.py#L10
