### ISSUE TITLE
Release v0.1 and blog post timeline

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/rechunker#9]
Hi @TomAugspurger! Sorry that I've let work on rechunker slide. The cloud migration kind of took over all my available bandwidth. But I'm scheduled to present about rechunker at the ESIP meeting next Tuesday (July 14) at 4pm ET. This gives a nice deadline to get something released.

I plan to work on rechunker more-or-less full time on Monday afternoon and Tuesday. My goals are
- [x] clean up the code and user-facing API
- [x] get some minimal docs written and deployed
- [x] write up a Medium blog post

If you have any time on those two days, I'd love to coordinate efforts. But if not, no worries!

**Comment by TomAugspurger** [comment]
I'll be offline for the next 3 days, but I'll be back on Monday. I should
have some time then.

**Comment by TomAugspurger** [comment]
0.1 is out and announced.

**Comment by rabernat** [comment]
Didn't we technically release 0.0.1? 😉
